FROM node:20-alpine

WORKDIR /app

# Спочатку копіюємо тільки файли залежностей
COPY package*.json ./

# Встановлюємо залежності
RUN npm install

# Тепер копіюємо решту коду
COPY . .

# Відкриваємо порт
EXPOSE 3000

# Запускаємо в режимі розробки
CMD ["npm", "run", "dev"]