tunnel: 2be39487-878c-4780-a32e-e55a82d8e335
credentials-file: /etc/cloudflared/2be39487-878c-4780-a32e-e55a82d8e335.json

ingress:
  - hostname: dev.ohmyrevit.pp.ua
    service: http://nginx:80
  - service: http_status:404