"""Add product ratings system

Revision ID: 86a01d1806fb
Revises: '5fd21363e127'
Create Date: 2025-12-29 15:39:57.458099+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a01d1806fb'
down_revision = '5fd21363e127'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create product_ratings table
    op.create_table(
        'product_ratings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'product_id', name='unique_user_product_rating'),
        sa.CheckConstraint('rating >= 1 AND rating <= 5', name='rating_range_check')
    )
    op.create_index(op.f('ix_product_ratings_product_id'), 'product_ratings', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_ratings_user_id'), 'product_ratings', ['user_id'], unique=False)

    # Add rating columns to products table
    op.add_column('products', sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('products', sa.Column('ratings_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop rating columns from products table
    op.drop_column('products', 'ratings_count')
    op.drop_column('products', 'average_rating')

    # Drop product_ratings table
    op.drop_index(op.f('ix_product_ratings_user_id'), table_name='product_ratings')
    op.drop_index(op.f('ix_product_ratings_product_id'), table_name='product_ratings')
    op.drop_table('product_ratings')
    # ### end Alembic commands ###