"""Add marketplace creator models and fields

Revision ID: 15aacdf498a0
Revises: 'd0e892376c2c'
Create Date: 2025-12-29 12:43:16.908997+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15aacdf498a0'
down_revision = 'd0e892376c2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Створюємо Enum тип ПЕРЕД використанням
    moderation_status_enum = sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'HIDDEN', name='moderationstatus')
    moderation_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('products', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('moderation_status', moderation_status_enum, nullable=True))
    op.add_column('products', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('moderated_by_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['moderated_by_id'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['author_id'], ['id'])
    op.add_column('users', sa.Column('is_creator', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('creator_balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'creator_balance')
    op.drop_column('users', 'is_creator')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'moderated_at')
    op.drop_column('products', 'moderated_by_id')
    op.drop_column('products', 'rejection_reason')
    op.drop_column('products', 'moderation_status')
    op.drop_column('products', 'author_id')

    # Видаляємо Enum тип
    sa.Enum(name='moderationstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###