"""Add applied_at and requested_at timestamps to creators

Revision ID: 5fd21363e127
Revises: '128734904ee7'
Create Date: 2025-12-29 12:56:26.805694+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd21363e127'
down_revision = '128734904ee7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Створюємо Enum тип ПЕРЕД використанням
    payout_status_enum = sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'REJECTED', 'FAILED', name='payoutstatus')
    payout_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('creator_applications', sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('creator_payouts', sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('creator_payouts', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=payout_status_enum,
               existing_nullable=True,
               postgresql_using='status::text::payoutstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('creator_payouts', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'REJECTED', 'FAILED', name='payoutstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('creator_payouts', 'requested_at')
    op.drop_column('creator_applications', 'applied_at')

    # Видаляємо Enum тип
    sa.Enum(name='payoutstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###